
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-27T10:30:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7844bec50b93c8711ae703840b1a0e43b8283df6",
 "version": "2.0a8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
