""" This file is automatically generated from "mitsuba.conf" using the script
    "resources/configure.py". Please do not attempt to change it manually,
    as any changes will be overwritten."""

PYTHON_EXECUTABLE = r"/private/var/folders/nj/wh528zms06j9t8y7bmlvpmjm0000gn/T/cibw-run-uswgqgr1/cp312-macosx_arm64/build/venv/bin/python"
MI_DEFAULT_VARIANT = ''
MI_VARIANTS = ['scalar_mono', 'scalar_mono_double', 'scalar_mono_polarized', 'scalar_mono_polarized_double', 'scalar_rgb', 'scalar_spectral', 'llvm_ad_rgb']
DRJIT_VERSION_REQUIREMENT = '0.4.6'
CXX_COMPILER = 'AppleClang 15.0.0.15000100'
