# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-02 13:10
from __future__ import unicode_literals

import os

from django.core.management import call_command
from django.db import migrations
from django.core import serializers

fixture = 'initial_bank'


def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture)


def unload_fixture(apps, schema_editor):
    MyModel = apps.get_model('bank', 'Bank')
    MyModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
