
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-25T11:43:40-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9121bcce55d77f04b7c805a89ee2f86de74c00a1",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
