# Generated by Django 5.0.6 on 2024-07-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_orderphoto_order_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='photos',
        ),
        migrations.DeleteModel(
            name='OrderPhoto',
        ),
    ]
