# Generated by Django 5.0.6 on 2024-07-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_category_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to='images'),
        ),
    ]
