# Generated by Django 5.0.4 on 2024-07-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_media_likes_media_views_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='views',
            field=models.ManyToManyField(blank=True, default=0, related_name='views', to='backend.ipmodel'),
        ),
    ]
