import numpy as np
import matrix_module as mat_mod
m=int(input("Enter the no.of Rows:"))
n=int(input("Enter the no.of Columns:"))
A=mat_mod.readmatrix(m,n)
print("MATRIX A")
print(A)
B=mat_mod.readmatrix(m,n)
print("MATRIX B")
print(B)
C=mat_mod.add_matrix(A,B)
mat_mod.add_matrix(A,B)
print("ADDITION")
print(C)
D=mat_mod.sub_matrix(A,B)
mat_mod.sub_matrix(A,B)
print("SUBTRACTION")
print(D)
E=mat_mod.mul_matrix(A,B)
mat_mod.mul_matrix(A,B)
print("MULTIPLICATION")
print(E)
F=mat_mod.transposematrix(A)
print("Original Matrix")
mat_mod.printmatrix(A)
print("Transpose Matrix")
print(F)

