# Generated by Django 5.1.2 on 2024-10-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0008_rename_date_modified_allocationrequestreview_last_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationrequest',
            name='group',
        ),
    ]
