from _typeshed import Incomplete
from dojo.agents.base_agent import BaseAgent as BaseAgent
from dojo.observations import BaseObservation as BaseObservation

class MarketAgent(BaseAgent):
    DEFAULT_ETH: Incomplete
    obs: Incomplete
    def __init__(self) -> None: ...
    def set_obs(self, obs: BaseObservation) -> None: ...
    initial_portfolio: Incomplete
    def setup(self) -> None: ...
    def setup_live(self) -> None: ...
    def reward(self, obs: BaseObservation) -> float: ...
