# Generated by Django 5.0.4 on 2024-07-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_ipmodel_media_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='likes',
        ),
        migrations.AddField(
            model_name='media',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to='backend.ipmodel'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
