# Generated by Django 4.2.16 on 2024-10-06 22:49

import django.core.files.storage
from django.db import migrations, models
import mailqueue.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0007_auto_20200318_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=mailqueue.utils.get_storage,
                                   upload_to=mailqueue.utils.upload_to),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='sent',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Sent'),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='to_address',
            field=models.TextField(db_index=True, verbose_name='To'),
        ),
    ]
