# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runner_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bauplan_pb2 as bauplan__pb2

try:
    execution__plan__pb2 = bauplan__pb2.execution__plan__pb2
except AttributeError:
    execution__plan__pb2 = bauplan__pb2.execution_plan_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14runner_service.proto\x12\x07\x62\x61uplan\x1a\rbauplan.proto"\x0e\n\x0c\x46lightStream"\x0e\n\x0cQueryRequest2L\n\rRunnerService\x12;\n\x0bServeFlight\x12\x15.bauplan.QueryRequest\x1a\x15.bauplan.FlightStreamB?Z=github.com/BauplanLabs/playground/commander-service/protobufsb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runner_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals['DESCRIPTOR']._options = None
    _globals[
        'DESCRIPTOR'
    ]._serialized_options = b'Z=github.com/BauplanLabs/playground/commander-service/protobufs'
    _globals['_FLIGHTSTREAM']._serialized_start = 48
    _globals['_FLIGHTSTREAM']._serialized_end = 62
    _globals['_QUERYREQUEST']._serialized_start = 64
    _globals['_QUERYREQUEST']._serialized_end = 78
    _globals['_RUNNERSERVICE']._serialized_start = 80
    _globals['_RUNNERSERVICE']._serialized_end = 156
# @@protoc_insertion_point(module_scope)
