# coding: utf-8

"""
    RadarBox On Demand API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.3.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from radarbox.models.api_statistic_airport import ApiStatisticAirport
from typing import Optional, Set
from typing_extensions import Self

class ApiAircraftStatistic(BaseModel):
    """
    ApiAircraftStatistic
    """ # noqa: E501
    year: Optional[StrictInt] = None
    month: Optional[StrictInt] = None
    distance: Optional[Union[StrictFloat, StrictInt]] = None
    duration: Optional[Union[StrictFloat, StrictInt]] = None
    duration_runway: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="durationRunway")
    duration_runway_accuracy: Optional[StrictInt] = Field(default=None, alias="durationRunwayAccuracy")
    active_days: Optional[StrictInt] = Field(default=None, alias="activeDays")
    flights: Optional[StrictInt] = None
    airport_movements: Optional[List[ApiStatisticAirport]] = Field(default=None, alias="airportMovements")
    __properties: ClassVar[List[str]] = ["year", "month", "distance", "duration", "durationRunway", "durationRunwayAccuracy", "activeDays", "flights", "airportMovements"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiAircraftStatistic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in airport_movements (list)
        _items = []
        if self.airport_movements:
            for _item_airport_movements in self.airport_movements:
                if _item_airport_movements:
                    _items.append(_item_airport_movements.to_dict())
            _dict['airportMovements'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiAircraftStatistic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "year": obj.get("year"),
            "month": obj.get("month"),
            "distance": obj.get("distance"),
            "duration": obj.get("duration"),
            "durationRunway": obj.get("durationRunway"),
            "durationRunwayAccuracy": obj.get("durationRunwayAccuracy"),
            "activeDays": obj.get("activeDays"),
            "flights": obj.get("flights"),
            "airportMovements": [ApiStatisticAirport.from_dict(_item) for _item in obj["airportMovements"]] if obj.get("airportMovements") is not None else None
        })
        return _obj


