# Generated by Django 4.2.16 on 2024-10-02 08:42

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("kapt_ads", "0004_alter_ad_managers_location_identifier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdsPluginConf",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "number_of_ads",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of ads to print"
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[("kapt_ads/ad.html", "Default")],
                        default="kapt_ads/ad.html",
                        max_length=150,
                        verbose_name="Template",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kapt_ads.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ads configuration",
                "verbose_name_plural": "Ads configurations",
            },
            bases=("cms.cmsplugin",),
        ),
    ]
