# Generated by Django 5.0.6 on 2024-07-01 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_category_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='text',
        ),
    ]
