
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-24T12:18:14-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4288b4ad9cafef9373348770e6ddd126e1f99c3",
 "version": "2.48.1b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
