import numpy as np
from ._ir import IRArbWaveform

__all__ = ['NormalTranslator', 'PlayDDRTranslator']

class NormalTranslator:
    def get_envelope(self, ir_list): ...
    def translate_ir(self, ir_list: list) -> tuple[np.ndarray, str]: ...

class PlayDDRTranslator(NormalTranslator):
    def get_arb(self, ir_list): ...
    def translate_ir(self, ir_list: list) -> tuple[list[IRArbWaveform], str]: ...
