#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2405-35-g6debf034"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2405
#define NETGEN_VERSION_TWEAK 35
#define NETGEN_VERSION_HASH "g6debf034"
#endif // NETGEN_VERSION_HPP_INCLUDED
