# Generated by Django 5.1.2 on 2024-10-15 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadinspector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/cadinspector/entity/")),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_images",
                        to="cadinspector.entity",
                        verbose_name="Material image",
                    ),
                ),
            ],
        ),
    ]
