# Thank you ChatGPT
OPMUNTRINGER = [
    "Du er næsten færdig, kom så!",
    "Bare én hurtig registrering, så er du klar!",
    "Husk, det tager kun et minut!",
    "Du klarer det! Bare gør det nu.",
    "Hver registrering tæller – gå i gang!",
    "Du er så tæt på! Lad os få det gjort.",
    "Dit arbejde fortjener at blive registreret!",
    "En hurtig opdatering, og så er du fri!",
    "Det er aldrig for sent at registrere tiden.",
    "Du kan gøre det – bare tag det skridt!",
    "Forestil dig, hvor tilfreds du bliver bagefter.",
    "Bare én registrering – så er det klaret!",
    "Du har så meget at vise, lad os få det registreret!",
    "Du er dygtig, og din tid fortjener at blive set.",
    "Et lille skridt for dig, men stort for din registrering!",
    "Det føles godt at få det gjort, prøv det!",
    "Husk, at hver registrering er et skridt mod succes.",
    "Du har styr på det – lad os få det gjort!",
    "Livet bliver lettere, når du får registreret tiden.",
    "Tænk på det som en hurtig pause – så er du tilbage!",
    "Din tid er værdifuld – giv den opmærksomhed!",
    "Du kan klare det, tag et minut til det!",
    "Registrer din tid, så du kan nyde din frihed.",
    "Du er stærkere end du tror – kom i gang!",
    "Tiden flyver, lad os få registreret den!",
    "En hurtig registrering og så kan du slappe af.",
    "Du vil være glad for, at du gjorde det!",
    "Din indsats fortjener anerkendelse – registrer den!",
    "Lad os få afsluttet det, så du kan komme videre.",
    "Du har gjort det før – gør det igen!",
    "Husk, at det er en del af at være effektiv.",
    "Det er en lille opgave, men vigtig for dig.",
    "Du kan gøre det på 30 sekunder!",
    "Bare tag dig tid til at registrere – du har det i dig!",
    "Din tid er guld værd – lad os registrere det!",
    "En hurtig registrering, og så kan du tage en pause!",
    "Du er så dygtig, lad os få det registreret!",
    "Et skridt ad gangen – begynd med registreringen!",
    "Gør det nu, så kan du slappe af senere.",
    "Husk, at registrering er en del af dit arbejde.",
    "Dit fremtidige jeg vil takke dig for det!",
    "Bare en hurtig registrering – så er du færdig!",
    "Det er en del af din succes – registrer det!",
    "Tænk på, hvordan det vil føles, når det er gjort.",
    "Du har det i dig – lad os få det klaret!",
    "En registrering ad gangen, og du er på rette spor!",
    "Du klarer det! Bare tag det første skridt.",
    "Tiden er inde – lad os få registreret!",
    "Husk at fejre små sejre – start med registreringen!",
    "Du vil føle dig bedre, når det er gjort.",
    "Det er en vigtig del af dit arbejde – få det gjort!",
    "Husk at registrere, så din indsats ikke går tabt.",
]
