# coding: utf-8

"""
    RadarBox On Demand API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.3.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from radarbox.models.api_aircraft_type_utilization_period import ApiAircraftTypeUtilizationPeriod
from typing import Optional, Set
from typing_extensions import Self

class ApiAircraftTypeUtilization(BaseModel):
    """
    ApiAircraftTypeUtilization
    """ # noqa: E501
    aircraft_type: Optional[StrictStr] = Field(default=None, alias="aircraftType")
    total_aircraft: Optional[StrictInt] = Field(default=None, alias="totalAircraft")
    api_aircraft_utilization_periods: Optional[List[ApiAircraftTypeUtilizationPeriod]] = Field(default=None, alias="apiAircraftUtilizationPeriods")
    __properties: ClassVar[List[str]] = ["aircraftType", "totalAircraft", "apiAircraftUtilizationPeriods"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiAircraftTypeUtilization from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in api_aircraft_utilization_periods (list)
        _items = []
        if self.api_aircraft_utilization_periods:
            for _item_api_aircraft_utilization_periods in self.api_aircraft_utilization_periods:
                if _item_api_aircraft_utilization_periods:
                    _items.append(_item_api_aircraft_utilization_periods.to_dict())
            _dict['apiAircraftUtilizationPeriods'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiAircraftTypeUtilization from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aircraftType": obj.get("aircraftType"),
            "totalAircraft": obj.get("totalAircraft"),
            "apiAircraftUtilizationPeriods": [ApiAircraftTypeUtilizationPeriod.from_dict(_item) for _item in obj["apiAircraftUtilizationPeriods"]] if obj.get("apiAircraftUtilizationPeriods") is not None else None
        })
        return _obj


