
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-25T12:44:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7ce6a6150cf4a51d784703c256d7e59831a8eef",
 "version": "3.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
