# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: informaticsmatters/protobuf/accountserver/merchant_charge_message.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGinformaticsmatters/protobuf/accountserver/merchant_charge_message.proto\x12)informaticsmatters.protobuf.accountserver\"\xd2\x02\n\x15MerchantChargeMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x15\n\rmerchant_kind\x18\x02 \x01(\t\x12\x15\n\rmerchant_name\x18\x03 \x01(\t\x12\x13\n\x0bmerchant_id\x18\x04 \x01(\r\x12K\n\toperation\x18\x05 \x01(\x0e\x32\x38.informaticsmatters.protobuf.accountserver.OperationEnum\x12\x11\n\tauth_code\x18\x06 \x01(\r\x12\r\n\x05value\x18\x07 \x01(\t\x12\x0b\n\x03sqn\x18\x08 \x01(\r\x12\x0c\n\x04user\x18\x10 \x01(\t\x12\x0f\n\x07product\x18\x11 \x01(\t\x12\x0c\n\x04unit\x18\x12 \x01(\t\x12\x14\n\x0corganisation\x18\x13 \x01(\t\x12\x17\n\x0f\x61\x64\x64itional_data\x18\x1e \x01(\t\x12\x0b\n\x03\x65oc\x18\x1f \x01(\x08*\x85\x01\n\rOperationEnum\x12\x1e\n\x1aOPERATION_ENUM_UNSPECIFIED\x10\x00\x12\x1a\n\x16OPERATION_ENUM_STORAGE\x10\x01\x12\x1d\n\x19OPERATION_ENUM_PROCESSING\x10\x02\x12\x19\n\x15OPERATION_ENUM_MEMORY\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'informaticsmatters.protobuf.accountserver.merchant_charge_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OPERATIONENUM']._serialized_start=460
  _globals['_OPERATIONENUM']._serialized_end=593
  _globals['_MERCHANTCHARGEMESSAGE']._serialized_start=119
  _globals['_MERCHANTCHARGEMESSAGE']._serialized_end=457
# @@protoc_insertion_point(module_scope)
