# notoken887/cryptor.py

class TokenCryptor:
    def encrypt(self, string):
        reversed_string = string[::-1]  # Reverse the string
        encrypted_string = ''.join(char + '▓' for char in reversed_string)  # Insert `▓` between characters
        # Replace characters with symbols
        return (encrypted_string
                .replace('A', '🌼')
                .replace('B', '🐾')
                .replace('C', '🌈')
                .replace('D', '🚀')
                .replace('E', '🌍')
                .replace('F', '🎉')
                .replace('G', '🍕')
                .replace('H', '🎨')
                .replace('I', '⚡')
                .replace('J', '🔑')
                .replace('K', '🥡')
                .replace('L', '🌟')
                .replace('M', '🌻')
                .replace('N', '🐉')
                .replace('O', '💧')
                .replace('P', '🔔')
                .replace('Q', '🦄')
                .replace('R', '🌸')
                .replace('S', '🏆')
                .replace('T', '🛡️')  # Keep T
                .replace('U', '🐬')
                .replace('V', '🎈')
                .replace('W', '🎵')
                .replace('X', '🏮')
                .replace('Y', '🔮')
                .replace('Z', '🍀')
                .replace('a', '🦋')
                .replace('b', '🍭')
                .replace('c', '🧊')
                .replace('d', '🌊')
                .replace('e', '🍇')
                .replace('f', '🔥')
                .replace('g', '🌿')
                .replace('h', '🍂')
                .replace('i', '🍔')
                .replace('j', '💀')
                .replace('k', '🦚')
                .replace('l', '🍒')
                .replace('m', '🎀')
                .replace('n', '🌞')
                .replace('o', '🐢')
                .replace('p', '💼')
                .replace('q', '🥝')
                .replace('r', '🐧')
                .replace('s', '🥇')
                .replace('t', '🍉')  # Use a different emoji for 't'
                .replace('u', '🦦')
                .replace('v', '🐷')
                .replace('w', '🎂')
                .replace('x', '🌴')
                .replace('y', '🌽')
                .replace('z', '🧠')
                .replace('0', '🎳')
                .replace('1', '🌺')
                .replace('2', '🏰')
                .replace('3', '🐠')
                .replace('4', '🪴')
                .replace('5', '🍋')
                .replace('6', '🏈')
                .replace('7', '🐘')
                .replace('8', '🎭')
                .replace('9', '🍊')  # Use a different emoji for '9'
                .replace('.', '♫'))  # Convert period to ♫

    def decrypt(self, encrypted_token):
        # Replace `▓` with an empty space
        token_without_char = encrypted_token.replace('▓', '')  
        # Replace symbols back to characters
        return (token_without_char
                .replace('🌼', 'A')
                .replace('🐾', 'B')
                .replace('🌈', 'C')
                .replace('🚀', 'D')
                .replace('🌍', 'E')
                .replace('🎉', 'F')
                .replace('🍕', 'G')
                .replace('🎨', 'H')
                .replace('⚡', 'I')
                .replace('🔑', 'J')
                .replace('🥡', 'K')
                .replace('🌟', 'L')
                .replace('🌻', 'M')
                .replace('🐉', 'N')
                .replace('💧', 'O')
                .replace('🔔', 'P')
                .replace('🦄', 'Q')
                .replace('🌸', 'R')
                .replace('🏆', 'S')
                .replace('🛡️', 'T')  # Keep T
                .replace('🐬', 'U')
                .replace('🎈', 'V')
                .replace('🎵', 'W')
                .replace('🏮', 'X')
                .replace('🔮', 'Y')
                .replace('🍀', 'Z')
                .replace('🦋', 'a')
                .replace('🍭', 'b')
                .replace('🧊', 'c')
                .replace('🌊', 'd')
                .replace('🍇', 'e')
                .replace('🔥', 'f')
                .replace('🌿', 'g')
                .replace('🍂', 'h')
                .replace('🍔', 'i')
                .replace('💀', 'j')
                .replace('🦚', 'k')
                .replace('🍒', 'l')
                .replace('🎀', 'm')
                .replace('🌞', 'n')
                .replace('🐢', 'o')
                .replace('💼', 'p')
                .replace('🥝', 'q')
                .replace('🐧', 'r')
                .replace('🥇', 's')
                .replace('🍉', 't')  # Use the correct emoji for 't'
                .replace('🦦', 'u')
                .replace('🐷', 'v')
                .replace('🎂', 'w')
                .replace('🌴', 'x')
                .replace('🌽', 'y')
                .replace('🧠', 'z')
                .replace('🎳', '0')
                .replace('🌺', '1')
                .replace('🏰', '2')
                .replace('🐠', '3')
                .replace('🪴', '4')
                .replace('🍋', '5')
                .replace('🏈', '6')
                .replace('🐘', '7')
                .replace('🎭', '8')
                .replace('🍊', '9')  # Use the correct emoji for '9'
                .replace('♫', '.'))  # Convert ♫ back to period
