# Generated by Django 4.2.16 on 2024-10-01 09:50

# Django
from django.db import migrations

# Project
import kapt_ads.fields


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="text",
            field=kapt_ads.fields.QuillField(
                blank=True, null=True, verbose_name="Text"
            ),
        ),
    ]
