# Generated by Django 4.2.16 on 2024-10-01 16:40

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_ads", "0003_location_rename_date_end_ad_publication_date_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="identifier",
            field=models.SlugField(
                max_length=150, null=True, verbose_name="Identifier"
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                models.F("identifier"), name="unique_identifier"
            ),
        ),
    ]
