# Generated by Django 4.2.16 on 2024-10-02 09:33

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_ads", "0004_alter_ad_managers_location_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="publication_date_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Publication end date"
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="publication_date_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Publication start date"
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="target_url",
            field=models.URLField(
                blank=True,
                help_text="The URL that opens when the ad is clicked.",
                null=True,
                verbose_name="Target URL",
            ),
        ),
    ]
