# coding: utf-8

"""
    Peblar local REST API

    # General This document contains the specification of the WLAC local REST API. This API for local networks is supported by Peblar products from firmware versions 1.6 and onwards. Before the API can be accessed, it is required to be enabled in the advanced settings page of the chargers web interface. The endpoints described below can be reached via http://\\<local_ip\\>/api/wlac/v1/\\<endpoint_name\\> for example http://10.11.12.13/api/wlac/v1/evinterface. <br><br> <img src=\"./images/api_enable.png\"/> <br> 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyPeblar.models.ev_interface_response import EVInterfaceResponse

class TestEVInterfaceResponse(unittest.TestCase):
    """EVInterfaceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EVInterfaceResponse:
        """Test EVInterfaceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EVInterfaceResponse`
        """
        model = EVInterfaceResponse()
        if include_optional:
            return EVInterfaceResponse(
                cp_state = '',
                lock_state = True,
                charge_current_limit = 56,
                charge_current_limit_source = '',
                charge_current_limit_actual = 56,
                force1_phase = True
            )
        else:
            return EVInterfaceResponse(
        )
        """

    def testEVInterfaceResponse(self):
        """Test EVInterfaceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
