# coding: utf-8

"""
    Peblar local REST API

    # General This document contains the specification of the WLAC local REST API. This API for local networks is supported by Peblar products from firmware versions 1.6 and onwards. Before the API can be accessed, it is required to be enabled in the advanced settings page of the chargers web interface. The endpoints described below can be reached via http://\\<local_ip\\>/api/wlac/v1/\\<endpoint_name\\> for example http://10.11.12.13/api/wlac/v1/evinterface. <br><br> <img src=\"./images/api_enable.png\"/> <br> 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyPeblar.models.system_get200_response import SystemGet200Response

class TestSystemGet200Response(unittest.TestCase):
    """SystemGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemGet200Response:
        """Test SystemGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemGet200Response`
        """
        model = SystemGet200Response()
        if include_optional:
            return SystemGet200Response(
                product_pn = '',
                product_sn = '',
                firmware_version = '',
                wlan_signal_strength = 56,
                cellular_signal_strength = 56,
                uptime = 56,
                phase_count = 56,
                force1_phase_allowed = True,
                active_error_codes = [
                    56
                    ],
                active_warning_codes = [
                    56
                    ]
            )
        else:
            return SystemGet200Response(
        )
        """

    def testSystemGet200Response(self):
        """Test SystemGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
