# Form implementation generated from reading ui file '/tmp/tmphakv0h2w/jdAppStreamEdit-9.2/jdAppStreamEdit/ui/ValidateWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ValidateWindow(object):
    def setupUi(self, ValidateWindow):
        ValidateWindow.setObjectName("ValidateWindow")
        ValidateWindow.resize(400, 295)
        self.verticalLayout = QtWidgets.QVBoxLayout(ValidateWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=ValidateWindow)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.mode_box = QtWidgets.QComboBox(parent=ValidateWindow)
        self.mode_box.setObjectName("mode_box")
        self.mode_box.addItem("")
        self.mode_box.addItem("")
        self.mode_box.addItem("")
        self.mode_box.addItem("")
        self.horizontalLayout.addWidget(self.mode_box)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.output_field = QtWidgets.QPlainTextEdit(parent=ValidateWindow)
        self.output_field.setReadOnly(True)
        self.output_field.setObjectName("output_field")
        self.verticalLayout.addWidget(self.output_field)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ok_button = QtWidgets.QPushButton(parent=ValidateWindow)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout_2.addWidget(self.ok_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ValidateWindow)
        QtCore.QMetaObject.connectSlotsByName(ValidateWindow)

    def retranslateUi(self, ValidateWindow):
        _translate = QtCore.QCoreApplication.translate
        ValidateWindow.setWindowTitle(_translate("ValidateWindow", "Validate"))
        self.label.setText(_translate("ValidateWindow", "Mode:"))
        self.mode_box.setItemText(0, _translate("ValidateWindow", "Appstreamcli"))
        self.mode_box.setItemText(1, _translate("ValidateWindow", "Appstream-Util Normal"))
        self.mode_box.setItemText(2, _translate("ValidateWindow", "Appstream-Util Relax"))
        self.mode_box.setItemText(3, _translate("ValidateWindow", "Appstream-Util Strict"))
        self.ok_button.setText(_translate("ValidateWindow", "OK"))
