# Generated by Django 5.0.6 on 2024-07-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_media_image_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to=''),
        ),
    ]
