# Generated by Django 5.0.4 on 2024-07-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_category_options_alter_media_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user_id',
        ),
        migrations.AddField(
            model_name='like',
            name='ip_address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
