# Generated by Django 4.2.16 on 2024-10-02 08:59

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmsplugin_ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adspluginconf",
            name="template",
            field=models.CharField(
                choices=[("ads.html", "Default")],
                default="ads.html",
                max_length=150,
                verbose_name="Template",
            ),
        ),
    ]
