# Generated by Django 5.0.4 on 2024-07-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_like_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='backend.ipmodel'),
        ),
    ]
