# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('local_lang_name',), 'verbose_name': 'Tokia', 'verbose_name_plural': 'Tokiak'},
        ),
        migrations.AlterModelOptions(
            name='polygon',
            options={'verbose_name': 'Poligonoa', 'verbose_name_plural': 'Poligonoak'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.AddField(
            model_name='place',
            name='code',
            field=models.CharField(default='0', max_length=255, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='country_lang_name',
            field=models.CharField(default='a', max_length=255, verbose_name='Country language name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='lang_academ_name',
            field=models.CharField(default='s', max_length=255, verbose_name='Language Academy name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='local_lang_name',
            field=models.CharField(default='a', max_length=255, verbose_name='Local language name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='official_name',
            field=models.CharField(default='a', max_length=255, verbose_name='Official name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='added',
            field=models.DateField(auto_now_add=True, verbose_name='Gehituta'),
        ),
        migrations.AlterField(
            model_name='place',
            name='geotype',
            field=models.IntegerField(choices=[(0, 'Partzuergoa'), (1, 'Barrutia / Auzoa'), (2, 'Udalerria / Hiria'), (3, 'Bailara / Eskualdea'), (4, 'Probintzia'), (5, 'Estatua'), (6, 'Herrialdea')], db_index=True, default=0, verbose_name='Mota'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Latitudea'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Longitudea'),
        ),
        migrations.AlterField(
            model_name='place',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Editatuta'),
        ),
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Oharrak'),
        ),
        migrations.AlterField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_set', to='geodata.Place', verbose_name='Gurasoa'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='added',
            field=models.DateField(auto_now_add=True, verbose_name='Gehituta'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='encode_levels',
            field=models.TextField(blank=True, null=True, verbose_name='Kodetutako mailak'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='encode_numlevels',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kodetzeko maila kopurua'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='encode_points',
            field=models.TextField(blank=True, null=True, verbose_name='Kodetutako puntuak'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='encode_zoomfactor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kodetzeko zoom faktorea'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='is_exterior',
            field=models.BooleanField(default=1, verbose_name='Kanpoaldekoa da'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='is_visible',
            field=models.BooleanField(default=1, verbose_name='Ikusgarria da'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='limits',
            field=models.TextField(blank=True, null=True, verbose_name='Mugak'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Editatuta'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.Place', verbose_name='Tokia'),
        ),
    ]
