# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_auto_20160912_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='country_lang_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country language name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lang_academ_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Language Academy name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='official_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Official name'),
        ),
    ]
