# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_auto_20160912_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Kodea'),
        ),
        migrations.AlterField(
            model_name='place',
            name='country_lang_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Izena estatuko hizkuntzan'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lang_academ_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Izen akademikoa'),
        ),
        migrations.AlterField(
            model_name='place',
            name='local_lang_name',
            field=models.CharField(max_length=255, verbose_name='Izena bertako hizkuntzan'),
        ),
        migrations.AlterField(
            model_name='place',
            name='official_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Izen ofiziala'),
        ),
    ]
