# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2023-01-31 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_auto_20160916_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Editatua'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Editatua'),
        ),
    ]
